sudo: required
language: erlang
otp_release:
  - 19.3
  - 18.3
  - 17.3
  - R16B03
  - R15B03
  - R14B04
before_install:
  - |
    docker run --rm \
               -v ${HOME}:${HOME} \
               -v /etc/passwd:/etc/passwd \
               -u $(id -u) \
               -w ${PWD} \
               -e PATH=${PATH} \
               silex/emacs:${EMACS} \
               -Q --batch -l test/package-install-deps.el
services:
  - docker
env:
  - EMACS=24
  - EMACS=25
script:
  - |
    docker run --rm \
               --net=host \
               -v ${HOME}:${HOME} \
               -v /etc/passwd:/etc/passwd \
               -u $(id -u) \
               -w ${PWD} \
               -e PATH=${PATH} \
               --entrypoint /bin/bash \
               silex/emacs:${EMACS} \
               --norc -c 'make test'
